repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/pre-commit/mirrors-php-cs-fixer
    rev: v3.64.0
    hooks:
      - id: php-cs-fixer
        files: \.(php)$

  - repo: local
    hooks:
      - id: phpstan
        name: phpstan
        entry: phpstan analyse --no-progress --error-format=raw
        language: system
        types: [php]
        pass_filenames: false

      - id: php-lint
        name: php-lint
        entry: find . -name '*.php' -not -path './vendor/*' -exec php -l {} \;
        language: system
        pass_filenames: false
